# Generated by Django 5.0.6 on 2024-07-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Piping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('inner_diameter', models.FloatField()),
                ('outer_diameter', models.FloatField()),
                ('material', models.CharField(max_length=50)),
                ('pipe_type', models.CharField(choices=[('discharge', 'Discharge Line'), ('liquid', 'Liquid Line'), ('condensing', 'Condensing Line'), ('suction', 'Suction Line')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='checkvalve',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkvalve',
            name='flow_capacity',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkvalve',
            name='material',
            field=models.CharField(default=0.0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkvalve',
            name='model',
            field=models.CharField(default='default_model', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkvalve',
            name='pressure_rating',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkvalve',
            name='size',
            field=models.CharField(default=0.0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compressor',
            name='additional_constraints',
            field=models.JSONField(default='[]', help_text='Additional constraints as JSON in Celsius, e.g., [{"field_points": [{"T_evap": 7, "T_cond": 40}, ...], "message": "Constraint message"}]'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compressor',
            name='displacement_50Hz',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compressor',
            name='displacement_60Hz',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compressor',
            name='max_pressure_hp',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compressor',
            name='max_pressure_lp',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compressor',
            name='refrigerants',
            field=models.JSONField(default='[]'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compressor',
            name='working_field_points',
            field=models.JSONField(default='[]', help_text='List of working field points as JSON in Celsius, e.g., [{"T_evap": 0, "T_cond": 40}, ...]'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkvalve',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
