# Generated by Django 5.0.6 on 2024-07-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_piping_checkvalve_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compressor',
            name='discharge_conn',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compressor',
            name='oil_conn',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compressor',
            name='suction_conn',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
