# Generated by Django 5.0.6 on 2024-07-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_piping_pipe_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='OilReceiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oil_receiver_model', models.CharField(max_length=20)),
                ('manufacturer', models.CharField(max_length=20)),
                ('oil_receiver_conn', models.FloatField()),
                ('oil_receiver_conn_oil', models.FloatField()),
                ('oil_receiver_pressure_max', models.FloatField()),
                ('oil_receiver_temp_min', models.FloatField()),
                ('oil_receiver_temp_max', models.FloatField()),
                ('oil_receiver_volume', models.FloatField()),
                ('oil_receiver_refrigerants', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='OilSeparator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oil_separator_model', models.CharField(max_length=20)),
                ('manufacturer', models.CharField(max_length=20)),
                ('oil_separator_conn', models.FloatField()),
                ('oil_separator_conn_oil', models.FloatField()),
                ('accumulator_pressure_max', models.FloatField()),
                ('accumulator_temp_min', models.FloatField()),
                ('accumulator_temp_max', models.FloatField()),
                ('accumulator_discharge', models.FloatField()),
                ('accumulator_refrigerants', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='OilSeparatorReceiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oil_separator_receiver_model', models.CharField(max_length=20)),
                ('manufacturer', models.CharField(max_length=20)),
                ('oil_separator_receiver_conn', models.FloatField()),
                ('oil_separator_receiver_conn_oil', models.FloatField()),
                ('oil_separator_receiver_pressure_max', models.FloatField()),
                ('oil_separator_receiver_temp_min', models.FloatField()),
                ('oil_separator_receiver_temp_max', models.FloatField()),
                ('oil_separator_receiver_volume', models.FloatField()),
                ('oil_separator_receiver_discharge', models.FloatField()),
                ('oil_separator_receiver_refrigerants', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='SightGlass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sightglass_model', models.CharField(max_length=20)),
                ('manufacturer', models.CharField(max_length=20)),
                ('sightglass_conn', models.FloatField()),
                ('sightglass_pressure', models.FloatField()),
                ('sightglass_refrigerants', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='SuctionAccumulator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accumulator_model', models.CharField(max_length=20)),
                ('manufacturer', models.CharField(max_length=20)),
                ('accumulator_conn', models.FloatField()),
                ('accumulator_pressuremin', models.FloatField()),
                ('accumulator_pressuremax', models.FloatField()),
                ('accumulator_tempmin', models.FloatField()),
                ('accumulator_tempmax', models.FloatField()),
                ('accumulator_refrigerants', models.JSONField()),
            ],
        ),
        migrations.RenameField(
            model_name='checkvalve',
            old_name='material',
            new_name='checkvalve_conn',
        ),
        migrations.RenameField(
            model_name='checkvalve',
            old_name='flow_capacity',
            new_name='checkvalve_kv',
        ),
        migrations.RenameField(
            model_name='checkvalve',
            old_name='pressure_rating',
            new_name='checkvalve_maxtemperature',
        ),
        migrations.RenameField(
            model_name='checkvalve',
            old_name='model',
            new_name='checkvalve_model',
        ),
        migrations.RenameField(
            model_name='checkvalve',
            old_name='name',
            new_name='checkvalve_name',
        ),
        migrations.RenameField(
            model_name='checkvalve',
            old_name='size',
            new_name='manufacturer',
        ),
        migrations.RenameField(
            model_name='receiver',
            old_name='name',
            new_name='receiver_name',
        ),
        migrations.RemoveField(
            model_name='checkvalve',
            name='description',
        ),
        migrations.AddField(
            model_name='checkvalve',
            name='checkvalve_mintemperature',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkvalve',
            name='checkvalve_pressure',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receiver',
            name='manufacturer',
            field=models.CharField(default='empty', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receiver',
            name='receiver_conn_in',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receiver',
            name='receiver_conn_out',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receiver',
            name='receiver_maxpressure',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receiver',
            name='receiver_orientation',
            field=models.CharField(choices=[('vertical', 'Vertical'), ('horizontal', 'Horizontal')], default='vertical', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receiver',
            name='receiver_refrigerant',
            field=models.CharField(default=[], help_text='Type of refrigerant the receiver is compatible with', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receiver',
            name='receiver_volume',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
